services:
  go-api:
    build:
      context: .  # Build from current directory (contains Dockerfile, go.mod, main.go)
    container_name: go-api
    restart: unless-stopped
    environment:
      - LISTEN_PORT=8080
      - SMTP_HOST=mail-service-vm.francecentral.cloudapp.azure.com
      - SMTP_PORT=587
      - SMTP_FROM=admin@mail-service-vm.francecentral.cloudapp.azure.com
    networks:
      - mail-network

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - go-api
    networks:
      - mail-network

networks:
  mail-network:
    driver: bridge