services:
  go-api:
    build:
      context: .
    container_name: go-api
    restart: unless-stopped
    ports:
      - "8081:8080"  # Host:8081 -> Container:8080 (für direkten Zugriff testen)
    environment:
      - LISTEN_PORT=8080
      - SMTP_HOST=mail-service-vm.francecentral.cloudapp.azure.com
      - SMTP_PORT=587
      - SMTP_FROM=admin@mail-service-vm.francecentral.cloudapp.azure.com
    networks:
      - mail-network

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"  # Host:8080 -> Container:80 (Standard-Nginx-Port)
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go-api
    networks:
      - mail-network

networks:
  mail-network:
    driver: bridge