version: '3.8'

services:
  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api
    restart: unless-stopped
    network_mode: "host"
    # ports:
    #   - "8081:8080"
    # extra_hosts:
    #   - "mail-service-vm.francecentral.cloudapp.azure.com:10.50.1.7"
    environment:
      - POSTFIX_FQDN=mail-service-vm.francecentral.cloudapp.azure.com
      - POSTFIX_CONNECT_IP=10.50.1.7
      - POSTFIX_PORT=587
      - DEFAULT_SENDER=admin@mail-service-vm.francecentral.cloudapp.azure.com
      - LISTEN_PORT=8080
    # networks:
    #   - mail-network

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go-api
    network_mode: "host" 
    # networks:
    #   - mail-network

# networks:
#   mail-network:
#     driver: bridge