version: '3.8'

services:
  # Go API service
  go-api:
    build:
      context: ./mailAPI/api  # Points to the 'api' directory to build the Docker image
    container_name: go-api
    restart: unless-stopped
    environment:
      - LISTEN_PORT=8080  # Internal port where the Go app listens
      # Database and Postfix variables removed for this test.
      # Ensure Go code handles missing variables gracefully.

  # Nginx as a simple reverse proxy (HTTP only for testing)
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"  # Maps the HTTP port
    volumes:
      # Mount custom Nginx configuration (simplified version)
      - ./nginx/nginx-simple.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - go-api