services:
  go-api:
    build:
      context: .
      dockerfile: mailservice/Dockerfile
    container_name: go-api
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTFIX_CONNECT_IP=host.docker.internal
      - POSTFIX_PORT=25
      - LISTEN_PORT=8080
    networks:
      - mail-network

  bounceservice:
        build:
          context: ./bounceservice
          dockerfile: bounceservice/Dockerfile
        container_name: bounce-service-api
        restart: unless-stopped
        ports:
          - "8081:8081"
        volumes: 
          - /var/log/mail.log:/data/mail.log:ro
        networks:
          - mail-network

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - go-api
      - bounceservice 
    networks:
      - mail-network

networks:
  mail-network:
    driver: bridge