services:
  go-api:
    build:
      context: .
      dockerfile: mailservice/Dockerfile
    container_name: go-api
    restart: unless-stopped
    depends_on:
      - nats # Stellt sicher, dass NATS vor dem go-api gestartet wird
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTFIX_CONNECT_IP=host.docker.internal
      - POSTFIX_PORT=25
      - LISTEN_PORT=8080
      - NATS_URL=nats://nats:4222 # Verbindungs-URL für den NATS-Service
    networks:
      - mail-network

  bounceservice:
    build:
      context: ./bounceservice
      dockerfile: Dockerfile
    container_name: bounce-service-api
    restart: unless-stopped
    depends_on:
      - nats # Stellt sicher, dass NATS vor dem bounceservice gestartet wird
    ports:
      - "8081:8081"
    volumes: 
      - /var/log/mail.log:/data/mail.log:ro
    environment:
      - NATS_URL=nats://nats:4222 # Verbindungs-URL für den NATS-Service
    networks:
      - mail-network

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - go-api
      - bounceservice 
    networks:
      - mail-network

  # --- HIER IST DER NEUE NATS-SERVICE ---
  nats:
    image: nats:2.10
    container_name: nats-server
    # Der '-js' Befehl aktiviert die JetStream-Engine für persistente Nachrichten
    command: "-js -m 8222" 
    restart: unless-stopped
    ports:
      - "4222:4222"  # Port für Client-Verbindungen
      - "8222:8222"  # HTTP-Port für Monitoring
    networks:
      - mail-network
  # --- ENDE DES NEUEN NATS-SERVICE ---

networks:
  mail-network:
    driver: bridge

