
services:
  go-api:
    build:
      context: .
      dockerfile: mailservice/Dockerfile
    container_name: go-api
    restart: unless-stopped
    environment:
      - POSTFIX_FQDN=localhost
      - POSTFIX_CONNECT_IP=127.0.0.1
      - POSTFIX_PORT=25
      - DEFAULT_SENDER=azureadmin@mail-service-vm.francecentral.cloudapp.azure.com
      - LISTEN_PORT=8080
    networks:
      - mail-network

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx-simple.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - go-api
    networks:
      - mail-network

networks:
  mail-network:
    driver: bridge