services:
  db-migrator:
    image: liquibase/liquibase:4.23.1
    container_name: liquibase-migrator
    depends_on:
      mail-postgres:
        condition: service_healthy
    volumes:
      - ./db-migrator/migrations:/liquibase/changelog
    environment:
      - URL=jdbc:postgresql://mail-postgres:5432/maildb
      - USERNAME=postgres
      - PASSWORD=postgres
      - CHANGE_LOG_FILE=changelog/master.xml
      - LIQUIBASE_COMMAND=update
    networks:
      - mail-network

networks:
  mail-network:
    name: mail-network
    external: true