services:
  db-migrator:
    image: liquibase/liquibase:4.23.1
    container_name: liquibase-migrator
    volumes:
      - ./db-migrator/migrations:/liquibase/changelog
    environment:
      - URL=jdbc:postgresql://host.docker.internal:5432/maildb  # Connect via host
      - USERNAME=postgres
      - PASSWORD=postgres
      - CHANGE_LOG_FILE=db-migrator/migrations/master.xml
      - LIQUIBASE_COMMAND=update
    extra_hosts:
      - "host.docker.internal:host-gateway"