# /variables/mail.yaml

# --- Server-Identität ---
public_fqdn: "mail.edeka-inforservice.duckdns.org"
main_domain: "edeka-inforservice.duckdns.org"

# --- E-Mail-/Marken-Identität ---
sending_domain: "edeka-inforservice.duckdns.org"

# --- Interne Server-Konfiguration ---
postfix_internal_fqdn_for_generic_map: "mail-service-vm.internal.cloudapp.net"

# --- Benutzerkonfiguration ---
mail_user: "azureadmin"
admin_email: "tobias.voegele@edeka.de"

# --- Absender-Umschreibungen ---
sender_canonical_mappings:
  - { key: 'root', value: 'hostmaster@edeka-inforservice.duckdns.org' }
  - { key: 'azureadmin', value: 'admin@edeka-inforservice.duckdns.org' }
  - { key: 'postmaster', value: 'hostmaster@edeka-inforservice.duckdns.org' }
  - { key: 'abuse', value: 'hostmaster@edeka-inforservice.duckdns.org' }
  - { key: 'www-data', value: 'webmaster@edeka-inforservice.duckdns.org' }