---
- name: Setup Ansible Vault password file
  hosts: localhost
  connection: local
  vars:
    vault_password: "12345"
    vault_password_file: "./vault_pass"
  
  tasks:
    - name: Create vault password file
      ansible.builtin.copy:
        dest: "{{ vault_password_file }}"
        content: "{{ vault_password }}\n"
        mode: '0600'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"